[package]
name = "aetherlink-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aetherlink-proto.workspace = true
blake3.workspace = true
libc.workspace = true
memmap2.workspace = true
prost.workspace = true
rcgen.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true

[dev-dependencies]
aetherlink-proto.workspace = true
anyhow.workspace = true
blake3.workspace = true
libc.workspace = true
tokio = { workspace = true, features = ["test-util"] }
